name: Unit Tests

on: [pull_request, push]


jobs:
  prepare_matrix:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.generate-matrix.outputs.versions }}
    steps:
    - name: Generate Node.js versions matrix
      id: generate-matrix
      run: |
        sudo apt-get install -y lynx
        lynx -dump https://endoflife.date/nodejs | grep -E -o '[0-9]+ \(LTS\)' | grep -E -o '([0-9]+)' > eol.list
        cat eol.list
        next_lts=$(cat eol.list | head -1)
        current_lts=$(cat eol.list | head -2 | tail -1)
        previous_lts=$(cat eol.list | head -3 | tail -1)
        VERSIONS="[$previous_lts, $current_lts, $next_lts]"
        echo ::set-output name=versions::${VERSIONS}

  test:
    needs:
    - prepare_matrix
    strategy:
      matrix:
        node-version: ${{ fromJSON(needs.prepare_matrix.outputs.versions) }}
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i -g npm
      name: Update NPM
    - run: npm install --no-package-lock
      name: Install dev dependencies
    - run: npm run lint
      name: Run linter
    - run: npm run test
      name: Run unit tests
